### ISSUE TITLE
Error message not displayed when using AJAX-based pop-up editing

### ISSUE THREAD

**Issue by peth-systopia** [Project60/org.project60.sepa#393] opened 2016-06-07 13:39 UTC
If you want to delete a contribution that is linked to a mandate, an error message should be displayed that this is not possible (as well as the ID of the linked mandate). However, if you use AJAX-based pop-up editing, the error is not displayed, but the form just keeps loading.

**Comment by Fabian-SYSTOPIA** [comment] 2016-10-27 12:42
Can confirm this still happens on 4.7

**Comment by Fabian-SYSTOPIA** [comment] 2016-11-25 13:30
The problem still seems to exist (using 1.2.4 alpha & CiviCRM 4.7.13 and 4.6.21)

**Comment by systopia** [comment] 2016-11-28 07:10
Well, with https://github.com/Project60/org.project60.sepa/commit/4521c843808eeb195526260b843ebd4a9b13c4db we now produce a proper exception, I added an APIWrapper to return a proper API error, and also added a feature that would remove the 'delete' link in a contribution search result. 

The problem is, however, that the AJAX calls from the UI do not use the API and cannot deal with an exception on the server side. I will create an official ticket, this needs to be fixed in core.

**Closed** 2016-11-29 08:15 UTC
Labels: bug, CiviCRM 4.6, CiviCRM 4.7

**Comment by systopia** [comment] 2016-12-02 14:18
There was still an issue with this, some calls needed an extra include. Should be fixed with https://github.com/Project60/org.project60.sepa/commit/c1df885b8b146ea3f85434d014b73bc5e3d70cd5
