### ISSUE TITLE
Problems publishing docs

### ISSUE THREAD

**Issue by francescbassas** [Project60/org.project60.sepa#723] opened 2024-06-18 15:09 UTC
I think something is broken in the docs publisher system. I can't see changes introduced here https://github.com/Project60/org.project60.sepa/pull/711

If I try to force publish I get this error:

![imatge](https://github.com/Project60/org.project60.sepa/assets/1064675/64a78f48-bc21-4e11-80c4-9fc37a3d2245)

**Comment by bjendres** [comment] 2024-06-19 06:38
has this been solved, @francescbassas ?

**Comment by bjendres** [comment] 2024-06-19 06:39
> has this been solved, @francescbassas ? Or why did you close [Project60/org.project60.sepapp#33](https://github.com/Project60/org.project60.sepapp/issues/33) ?

Ah, sorry, got it m(

**Comment by bjendres** [comment] 2024-08-02 09:05
@jofranz Could you have a look at this please?

**Comment by jofranz** [comment] 2024-09-02 12:19
This got fixed by the core team after my [request](https://chat.civicrm.org/civicrm/pl/f644dz1o4t8aje8wta5yzmck9y) in CiviCRM Mattermost.
It might have been caused by force pushing to master leaving the version on their server in an undefined state.

**Comment by francescbassas** [comment] 2024-09-02 14:33
Great! Thanks @jofranz

**Closed** 2024-09-02 14:33 UTC
Labels: documentation, bug
