### ISSUE TITLE
Links at mandate should be restored after each event at Contributions tab

### ISSUE THREAD

**Issue by scardinius** [Project60/org.project60.sepa#481] opened 2018-04-12 15:10 UTC
After change status of a contribution whole Contributions tab is reloaded. And therefore link "edit mandate" disapears. From links "View" and "edit mandate" there are default links "View", "Edit" and "Cancel".

This causes potentially unwanted case when user clicks at "Cancel" link. Then there is a discrepancy in database - recurring contribution is cancelled but mandate is still RCUR.

**Comment by systopia** [comment] 2018-10-09 15:45
I couldn't reproduce the issue, but since we have a separate SEPA tab now, I stripped the links in the 'Contributions' tab altogether. I hope this should solve the issue

Will be released in ``1.4``

**Closed by systopia** 2018-10-09 15:45 UTC
Labels: bug
