### ISSUE TITLE
'monthly' Button (not-clickable) appears on contribution-page without activation of recurring contributions

### ISSUE THREAD

**Issue by intombi** [Project60/org.project60.sepa#328] opened 2015-09-17 18:33 UTC
Hi, 

I tried to use the sepa payment processor on a test-contributionpage. The page does not include any recurring contribution-possibility. Regardless of this fact there appears a 'monthly' button when the sea-payment is selected. (See screenshot below) The button (or dropdownmenu) is not clickable... 

![screenshot](https://cloud.githubusercontent.com/assets/14223143/9942355/e19ebf60-5d7a-11e5-8405-063bdc246a95.png)

Deactivating all other payment processors did not work. Maybe I am missing something ... 

Regards

Fabian

**Comment by systopia** [comment] 2015-09-18 07:41
@intombi Thanks for the bug report. I couldn't reproduce it, so I would need your CiviCRM and your CiviSEPA version, and ideally a screenshot of you donation page's contribution settings.

**Comment by intombi** [comment] 2015-09-18 20:47
@systopia we are using Joomla 3.4.4 and CiviCRM 4.6.8. CiviSEPA is installed as Version 1.2rc1. I send you some screenshots via mail.

**Comment by systopia** [comment] 2015-09-21 08:36
Hi @intombi. I've uploaded your config screen shots. I hope that's o.k., but I couldn't spot any confidential data in there.

I'm sorry, but I have to tell you that reproducing/fixing an evasive bug on Joomla (which we rarely use) is more than I can do as a free community service.

Could somebody else reproduce this bug and narrow down the cuplrit? PRs very welcome...

**Comment by systopia** [comment] 2015-09-29 08:11
@intombi: Could you please confirm that the current [dev_328 branch](https://github.com/Project60/org.project60.sepa/tree/dev_328)  fixes your problem?

**Comment by intombi** [comment] 2015-09-30 15:26
it's working with dev_328

**Comment by systopia** [comment] 2015-09-30 16:46
I'll close this when it's merged.

**Comment by systopia** [comment] 2015-10-01 11:54
merged to 1.2.1 and master

**Closed by systopia** 2015-10-01 11:54 UTC
Labels: bug, funded, question
