### ISSUE TITLE
Activity date of contribution is overwritten by SEPA processing

### ISSUE THREAD

**Issue by mariav0** [Project60/org.project60.sepa#637] opened 2022-06-15 14:01 UTC
We have noticed that the existing activity date of a contribution will be overwritten after the contribution is set to Completed (after SEPA processing).
Has this been changed on purpose?
Now you can only find out in the SEPA mandate information when the contribution was made. But it can't be used in a report anymore.
This report is used to see when there are any new contributions. After the contribution is set to Completed old contributions will be shown again in the report.

Tested on Drupal 7
CiviCRM 5.47.4
CiviSEPA 1.6.0

**Comment by mariav0** [comment] 2022-06-22 10:58
Workaround: Creating an own Data Processor Reports solves the problem. The date when the activity was created stays the same while the activity date itself will be overwritten. Unfortunately, the creation date cannot be accessed via CiviReport.
The issue can also be closed if it is not or could not be interesting for anyone else.

**Comment by bjendres** [comment] 2022-07-04 12:56
> We have noticed that the existing activity date of a contribution will be overwritten after the contribution is set to Completed (after SEPA processing). 

How are you completing the contributions? Is this the "mark received" button, oder via the CiviBanking module? If it's the latter case, than this is by design.

**Comment by mariav0** [comment] 2022-07-18 09:56
Hi Björn,
it's completed by the "mark received" button. CiviBanking is not in place.

**Comment by bjendres** [comment] 2022-07-19 20:30
By "activity date" do you mean the date of the complimentary CiviCRM *activity*, right?

In any case, CiviSEPA should only do [this](https://github.com/Project60/org.project60.sepa/blob/1.6.1/CRM/Sepa/Logic/Group.php#L215-L219) update. If this has any (new) knock-on effects on the activity, all we could do is add mitigation code to undo this.

**Comment by jensschuppe** [comment] 2022-10-05 13:29
With a workaround in place (using the activity's creation date), we're closing this.

**Closed by jensschuppe** 2022-10-05 13:29 UTC
Labels: question
