### ISSUE TITLE
Transaction group contains contributors who were already charged

### ISSUE THREAD

**Issue by MarcMichalsky** [Project60/org.project60.sepa#575] opened 2020-06-09 12:36 UTC
Hello community,

we encountered a major problem in May, when contributors of a recurring transaction group, that was already transmitted to the bank on April 29th, were accidentally charged again twice (!) because an almost similar transaction group was generated again and again.

We were able to reproduce the error various times on a test server:

04-28-2020, close transaction group and transmit it to the bank
![Screenshot_CiviSEPA_1](https://user-images.githubusercontent.com/24728186/84143908-aaa46a80-aa57-11ea-8d40-15ea21275b62.png)

05-04-2020, import transactions via csv file

05-05-2020, refresh standing orders
![Screenshot_CiviSEPA_2](https://user-images.githubusercontent.com/24728186/84147338-864b8c80-aa5d-11ea-92eb-49c955f22be0.png)

Transaction group `TXG-2-RCUR-2020-05-01--2` contains all members of `TXG-2-RCUR-2020-05-01--1` and some more.

We noticed that the contributors that accidentally were charged multiple times had two entries for the same transaction in their payment history. 

Before importing bank transactions:
![Screenshot_CiviSEPA_3](https://user-images.githubusercontent.com/24728186/84145724-b5143380-aa5a-11ea-8f4a-8fde70290749.png)

After importing bank transactions:
![Screenshot_CiviSEPA_4](https://user-images.githubusercontent.com/24728186/84145700-a9c10800-aa5a-11ea-942e-0d77783dbc32.png)

The entries differ in their state and the date of receipt.

The only workaround we found is to set the tolerance for delayed transaction groups to 0 days. This ensures that transaction groups can not be generated for the past.

We hope that with your help we are able to find a satisfying and reliable solution to this problem.

**Comment by bjendres** [comment] 2020-06-09 12:40
Hi @MarcMichalsky. What are your settings for the creditor used?

**Comment by MarcMichalsky** [comment] 2020-06-09 12:53
Hi @bjendres, thanks for the fast answer!
This is our configuration:

![Screenshot_CiviSEPA_5](https://user-images.githubusercontent.com/24728186/84149471-d415c400-aa60-11ea-825a-1d4827953072.png)

**Comment by bjendres** [comment] 2020-06-09 13:10
Thanks. I think the problem is the large grace period (Toleranz), you shouldn't need more than a couple of days.

In this particular case, I assume what's happened is:
1. You didn't collect the May 1st group in time
2. When closing the May 1st group (too late) it would be adjusted to May 4th to still be collectible
3. When you then pressed the update button again, the original May 1st collection date was still within the grace period, so the algorithm was looking for existing contributions for May 1st - and couldn't find any because they were moved. So they were recreated.

 In general it's advisable to
* collect the groups on time
* keep the grace period low or zero
* horizon + grace should be well under the shortest collection period (here probably one month, so I would suggest a grace of 5 and a horizon of 20 days)

This way you avoid these hazards. When you *did* forget to submit a group in time, you should always proceed with caution.

I have added #576 to show how to potentially prevent this in code.

**Comment by MarcMichalsky** [comment] 2020-06-09 14:30
Hello @bjendres,
thanks a lot for your advice!

I don't think that the reason for the incident was that we collected the May 1st group too late. It was closed and submitted on April 28th. The faulty group was only generated after the the transaction CSV file was uploaded and processed.

To me it looks very suspicious that in the payment history of the double charged contributors the transaction appears twice: once with date May 1st and "in progress" and once with May 4th and "finished". It seems like the banking module does not match transactions with a different receipt date (e.g. May 4th) with the original SEPA mandate (e.g. May 1st).

I have tried your configuration suggestion (a grace of 5 and a horizon of 20 days) but the error still occurs.

**Comment by bjendres** [comment] 2020-06-10 06:11
> I don't think that the reason for the incident was that we collected the May 1st group too late. It was closed and submitted on April 28th. The faulty group was only generated after the transaction CSV file was uploaded and processed.

That's correct, but is had been deferred. I assumed it was because of a late submission, but it could also be due to config changes (or maybe other influences). In either case point 3 of the explanation above still stands: if you recalculate the groups, and the calculated collection date differs from the one for the previously generated (and potentially closed) group, it will not recognise it and create a new one.

@MarcMichalsky: Do you have an idea why it would've calculated the May 4th the first time, and May 1st the second time around? I could only think of config changes, or the first one being deferred upon (late) submission.

**Comment by MarcMichalsky** [comment] 2020-06-10 11:58
@bjendres 

> Do you have an idea why it would've calculated the May 4th the first time, and May 1st the second time around? I could only think of config changes, or the first one being deferred upon (late) submission.

Both times the calculated date was May 1st. Because of the holiday and the weekend the bank collected the money on May 4th. When I import and process the banks CSV file the included transactions get matched with the prebooked ones correctly. But when I refresh the transaction groups again, the transactions marked for May 4th are not getting recognized as the original May 1st group, so that the group is getting generated again – I suppose.

Here some pseudocode to describe what I think is happening:
![UML_Sequenzdiagramm](https://user-images.githubusercontent.com/24728186/84264940-587c4b80-ab22-11ea-9d40-1a412ada8594.png)

**Comment by MarcMichalsky** [comment] 2020-06-15 09:25
Hello @bjendres,

> Could you see if there is any process between the generated PAIN file and the bank execution that adjusts dates (without CiviSEPA knowing)?

There is no other process between downloading the CSV file from the bank and uploading it to Civi.

I already mentioned that both dates `booking_date` and `value_date` in the CSV file are the same (May 4th). I assume this is an error on the banks side because it turns out that the wrong date also shows up in the official bank statements (PDF file).

When I manually change the `booking_date` to May 1st, the preeboked contributions are still getting matched correctly but the faulty group gets generated again. When I manually change the `value_date` to May 1st, the preeboked contributions also get matched but the faulty group does not get generated. I think this is what happens usually, when it works correctly because there is no holiday and `value_date` and `booking_date` are the same. Unfortunately the manipulation of the `value_date` does not reflect reality, because it makes the transactions look like they were received on `value_date` what is not true. 

![Screenshot](https://user-images.githubusercontent.com/24728186/84640292-c39a9900-aef9-11ea-94b0-398ab4e3fc54.png)

*Import plugin configuration:*
```JSON
{
   "comment": "Buchungstag",
   "from": 8,
   "to": "booking_date",
   "type": "strtotime:d.m.y"
},
{
   "comment": "Wertstellungstag",
   "from": 7,
   "to": "value_date",
   "type": "strtotime:d.m.y"
}

**Comment by bjendres** [comment] 2020-06-15 15:26
The CiviBanking SEPA matcher uses ``value_date``. If that is not the date that the SEPA payment is *collected*, than this would explain your issue. 

This is, however, not an issue of CiviSEPA then. You could argue that it should be more resilient against date manipulations, which would be covered by the aforementioned #576.

**Comment by MarcMichalsky** [comment] 2020-06-15 16:04
The `value_date` **is** the date when the payments where collected. I corrected the `booking_date` manually but the error persists. 

The `booking_date` is the date when the bank should process the payments. We plan our booking dates for 1st and 15th of a month. Sometimes this dates fall on a holiday so the value dates differ.

In this case CiviSepa does not recognize that the collection for the specific booking date already took place and generates the same group again.

If the booking date differs from the value date CiviSepa should rely on the given booking date instead of the value date when calculating the groups.

**Comment by bjendres** [comment] 2020-06-18 15:56
Then I don't get it. In your first screen shot you can see that the first transaction is dated to May 4th, and the new group is generated for May 1st. Assuming that the first group was originally also dated to May 1st (since that's apparently what the algorithm does with your settings), the collection date in the file would be also be May 1st. Since that was a holiday (in Germany), that bank should've rejected that file. But instead *somebody* (the bank?) has adjusted the collection date to May 4th without telling CiviSEPA. It sounds weird that the bank would do that without any kind of checking back with the user. Could you maybe ask the bank if this is the designed behaviour?

**Comment by MarcMichalsky** [comment] 2020-06-18 16:11
Yes, I think the wrong booking date is an issue caused by the bank.
But I doubt that this is the reason for the mistake because my testing showed that CiviSepa refers to the value date of the contributions when it calculates the Sepa groups.

**Closed** 2020-06-23 15:52 UTC
Labels: bug, question
